spring:
  config:
    import: optional:configserver:http://localhost:8888
    name: notification-service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

hosts:
  logstash: logstash