stages:
  - sync

# 하위 모듈 b에서 상위 모듈 moim으로 변경 사항 반영
sync-to-moim:
  stage: sync
  script:
    - git subtree add --prefix=config https://github.com/sunsuking/ddalkak_config.git main --squash
    - git subtree add --prefix=tunneling https://github.com/sunsuking/tunelling.git master --squash
    - git subtree add --prefix=config https://github.com/sunsuking/ddalkak_config.git main --squash
    - git subtree add --prefix=server https://github.com/sunsuking/ddalkak.git master --squash
    - git subtree add --prefix=client https://github.com/ljjunh/ttalkak.git master --squash
