spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ddalkak
    username: ddalkak
    password: ddalkak
  data:
    redis:
      host: localhost
      port: 6379
      password: ddalkak
  
  jpa:
    hibernate:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: update
    show-sql: true
  kafka:
    consumer:
      group-id: deployment
    bootstrap-servers: localhost:9092
    
logging:
  level:
    com:
      ttalkak: DEBUG

eureka:
  instance:
    instance-id: ${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
  client:
    fetch-registry: true
    register-with-eureka: true

management:
  tracing:
    sampling:
      probability: 1.0

