server:
  port: 0

spring:
  config:
    import: optional:configserver:http://config-server:8888
    name: project-service

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
      
hosts:
  logstash: 34.64.227.45

